CREATE TABLE price_reports (
    id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255) REFERENCES app_user(id) ON DELETE CASCADE,
    product_id VARCHAR(255) REFERENCES product(id) ON DELETE CASCADE,
    store_id UUID REFERENCES store(id) ON DELETE CASCADE,
    price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);